name: appuniparthenope
description: "The official app of the University of Naples 'Parthenope,' developed by students, offers a tailored experience for the academic community. Whether you are a student, teacher, or part of the administrative staff, you will have quick and easy access to all essential university information. Explore the new minimalist interface inspired by our university's colors, designed to make navigation intuitive and enjoyable. Keep track of your academic activities, available rooms, and university events all in one place."

version: 4.0.2+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  
  animated_notch_bottom_bar: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.1
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1
  easy_search_bar: ^2.5.0
  intl: ^0.19.0  
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  geolocator: ^12.0.0
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  dots_indicator: ^3.0.0
  location: ^6.0.2
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  yaml: ^3.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  
flutter_native_splash:
  color: "#458bb1" # colore di sfondo blu
  image: assets/logo.png # immagine da mostrare al centro


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - pubspec.yaml
    - assets/logo.png
    - assets/logoWhite.png
    
    - assets/textLogo.png
    - assets/pta.png
    - assets/meteoUniLogo.png
    - assets/user_profile_default.jpg
    - assets/qrcode_default.png
    - assets/icon/coccarda.png
    - assets/icon/faceid.png
    - assets/icon/fingerprint.png
    - assets/icon/coccarda.svg
    - assets/Onda.png
    - assets/maps.png

    #lingua
    - assets/lang/
    - assets/lang/intl_en.arb
    - assets/lang/intl_it.arb

    # Icon Service Image:
    - assets/icon/services/student.png
    - assets/icon/services/tax.png
    - assets/icon/services/courses.png
    - assets/icon/services/weather.png
    - assets/icon/appointmentIcon.png
    - assets/icon/discussionIcon.png
    - assets/icon/practicalTest.png
    - assets/icon/services/libraryService.png
    - assets/icon/careerIcon.png
    - assets/icon/homeIcon.png
    - assets/icon/menubarIcon.png
    - assets/icon/logoutIcon.png

    # Icon Student Service Image:
    - assets/icon/services/careerStudent.png
    - assets/icon/services/courses2.png
    - assets/icon/services/tax2.png
    - assets/icon/services/weather2.png


    # Icon Prof Service Image:
    - assets/icon/services/lecture.png
    - assets/icon/services/classroom.png
    - assets/icon/services/events2.png
    - assets/icon/services/classroom2.png
    - assets/icon/services/classroom3.png

    # Icon Weather:
    - assets/icon/weather/Sole.png
    - assets/icon/weather/Neve.png
    - assets/icon/weather/Nuvoloso.png
    - assets/icon/weather/Pioggia.png
    - assets/icon/weather/Soleggiato.png
    - assets/icon/weather/Temporale.png
    - assets/icon/weather/default.png

    # Universitye Image:
    - assets/university/uni_monte.jpg
    - assets/university/uni_cdn.png
    - assets/university/uni_centrale.png 
    - assets/university/uni_medina.jpeg
    - assets/university/uni_nola.jpeg
    - assets/university/uni_villadoria.jpeg

    # Universitye Image Carousel:
    #Central
    - assets/university/caroselloSedi/SedeC1.jpg
    - assets/university/caroselloSedi/SedeC2.png
    - assets/university/caroselloSedi/SedeC3.png
    - assets/university/caroselloSedi/SedeC4.png
    - assets/university/caroselloSedi/SedeC5.png
    - assets/university/caroselloSedi/SedeC6.png
    #CDN
    - assets/university/caroselloSedi/SedeCD0.png
    - assets/university/caroselloSedi/SedeCD1.png
    - assets/university/caroselloSedi/SedeCD2.png
    - assets/university/caroselloSedi/SedeCD3.png
    - assets/university/caroselloSedi/SedeCD4.png
    - assets/university/caroselloSedi/SedeCD5.png
    - assets/university/caroselloSedi/SedeCD6.png
    - assets/university/caroselloSedi/SedeCD7.png
    - assets/university/caroselloSedi/SedeCD8.png
    #Medina
    - assets/university/caroselloSedi/SedeMed0.png
    - assets/university/caroselloSedi/SedeMed1.png
    #Pacanowski
    - assets/university/caroselloSedi/SedePaca0.png
    - assets/university/caroselloSedi/SedePaca1.png
    - assets/university/caroselloSedi/SedePaca2.png
    - assets/university/caroselloSedi/SedePaca3.png
    - assets/university/caroselloSedi/SedePaca4.png
    - assets/university/caroselloSedi/SedePaca5.png
    - assets/university/caroselloSedi/SedePaca6.png
    #VillaDA
    - assets/university/caroselloSedi/SedeVDA0.png
    - assets/university/caroselloSedi/SedeVDA1.png
    - assets/university/caroselloSedi/SedeVDA2.png
    - assets/university/caroselloSedi/SedeVDA3.png
    - assets/university/caroselloSedi/SedeVDA4.png
    - assets/university/caroselloSedi/SedeVDA5.png
    - assets/university/caroselloSedi/SedeVDA6.png

     # Contact Icon:
    - assets/icon/contact/fb.png
    - assets/icon/contact/ig.png
    - assets/icon/contact/linkedin.png
    - assets/icon/contact/uniparthenope.png
    - assets/icon/contact/youtube.png
    
    # Team Image:
    - assets/team/gm.jpg
    - assets/team/nn.jpg
    - assets/team/team_leader.jpg
    - assets/team/cc.png
    - assets/team/cgdv.png

    # Card Image:
    - assets/scanCode.jpg
    - assets/addUser.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


